name: Secret Scan

on:
  push:
  pull_request:

jobs:
  git-secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git make
          git clone https://github.com/awslabs/git-secrets.git
          cd git-secrets && sudo make install

      - name: Configure patterns
        run: |
          git secrets --register-aws
          git secrets --add 'password\s*='
          git secrets --add 'api[_-]?key\s*:'

      - name: Scan repository
        run: git secrets --scan -r .
